Don't perform health checks on depth images when disabled
Auterion/autopilot_manager pull request #56
Opened 2022-11-09 11:11 UTC by DanMesh

### Description

If the Autopilot Manager is installed and running, the _Sensor Manager_ and _Landing Manager_ still perform health checks on the depth image stream. If the RealSense is not connected, this will cause the user to receive a constant stream of error messages in AMC.

Going forward, we want to have safe landing installed and ready to use in AOS, which means Autopilot Manager will be running. However, when a user is not planning to use safe landing (no RealSense connected and `COM_OBS_AVOID` set to 0), they should not be aware of it and should definitely not receive errors.

#### Preferred alternative:

It would be better if this were slightly more configurable for the user.
There should be a user-accessible parameter (AMC) to explicitly disable safe landing, which would then completely stop the Autopilot Manager service or, at the very least, put it into a "standby"/"not active" mode.

### Test data / coverage

- [x] SITL (use model without the depth camera and get no errors)
- [ ] Skynode

---

**Jira Task:** [AVOID-287](https://auterion.atlassian.net/browse/AVOID-287)
**Backport needed?** No
**Documentation needed?** No

2022-11-15 14:10 UTC, jwidauer requested changes
Looks nice! Just had some small thoughts and found a data race that should probably be addressed! But otherwise I like it! :smile:

2022-11-15 14:10 UTC, jwidauer commented on src/AutopilotManager.cpp
> +        }
I'd consider using a switch statement here and maybe. That might make this a bit easier to read. I was thinking of something like:

```cpp
    switch (value) {
        case 0:
            std::cout << "Obstacle avoidance has been disabled.\n";
            _obstacle_avoidance_enabled = false;
           break;
       case 1:
           std::cout << "Obstacle avoidance has been enabled.\n";
            _obstacle_avoidance_enabled = true;
            break;
        default:
            std::cout << "Unexpected value for parameter \"COM_OBS_AVOID\": " << value << " Disabling obstacle avoidance!\n";
            _obstacle_avoidance_enabled = false;
    }
```

And if you take the approach with having separate functions for each module to enabled / disable it, you could create a small lambda before, so you don't have to have the same lines multiple times.

2022-11-15 14:55 UTC, DanMesh commented on src/AutopilotManager.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
I knew this would be controversial 😅 
But if we make it 1Hz (instead of something higher) this does look nicer.

2022-11-15 14:55 UTC, DanMesh commented on src/AutopilotManager.cpp
> +    const std::pair<mavsdk::Param::Result, int> result = _param->get_param_int("COM_OBS_AVOID");
Oo I like that - thanks!

2022-11-15 14:55 UTC, DanMesh commented on src/AutopilotManager.cpp
> +        }
My initial reaction was the same. However, since we're checking this every second, one of the logs will be printed every second, which isn't necessary (and is annoying if the frequency is increased).
That's why I've used the more complex `if (value_is_X && has_changed)` structure.

A slightly more readable alternative might be:
```cpp
const bool should_enable = value == 1 && !_obstacle_avoidance_enabled;
const bool should_disable = value == 0 && _obstacle_avoidance_enabled;
const bool invalid_value = value < 0 && value > 1;
if (should_enable) {
    _obstacle_avoidance_enabled = true;
    std::cout << autopilotManagerOut << "Obstacle avoidance has been enabled in PX4." << std::endl;
} else if (should_disable) {
    _obstacle_avoidance_enabled = false;
    std::cout << autopilotManagerOut << "Obstacle avoidance has been disabled in PX4." << std::endl;
} else if (invalid_value) {
    std::cout << autopilotManagerOut << "Unexpected value for parameter COM_OBS_AVOID: " << value << ". Obstacle avoidance assumed disabled!" << std::endl;
}
```

2022-11-15 14:55 UTC, DanMesh commented on src/AutopilotManager.cpp
> +            return _obstacle_avoidance_enabled.load();
Good catch. And that's a nice alternative for setting this OA parameter. It seems cleaner and more readable so I'll give it a try.

2022-11-16 16:28 UTC, jwidauer approved these changes
Neat! LGTM!

2022-11-16 16:51 UTC, merged