Create configuration script
Auterion/autopilot_manager pull request #57
Opened 2022-11-14 15:09 UTC by DanMesh

### Description

As suggested [here](https://github.com/Auterion/AuterionOS/pull/1819#discussion_r1017618219), this creates a single script that can be used to perform multiple configuration operations for the Autopilot Manager.
This replaces some bash aliases that had begun to be added in AOS.

#### Installation
(This should be done automatically during AOS installation).   
Once the Autopilot Manager is installed, create a symbolic link to the script in `/usr/local/bin`:

```sh
ln -s /usr/src/app/autopilot-manager/autopilot-manager/share/autopilot-manager/data/scripts/apm /usr/local/bin/
```

#### Usage

1. Update the `autopilot_manager.conf` config file used by the systemd service:   
   ```sh
   apm update-config
   ```
2. Enable and disable safe landing as the decision maker:   
   ```sh
   apm safe-landing enable
   apm safe-landing disable
   ```

#### Future use

This could eventually be used as a nicer way to change parameters when SSHed in (compared to editing them in the `.conf` file or ROS launch files).

Other config/debug/update functions also come to mind.

### Test data / coverage
Skynode

---

**Jira Task:** [AVOID-285](https://auterion.atlassian.net/browse/AVOID-285)

**Does this PR need to be backported to the stable release?**
No

**Does this PR need to update any documentation (readme, confluence, gitbook, etc.)?**
Yes, we should document this

2022-11-14 19:34 UTC, TSC21 requested changes
Please move this to the `tools` folder at the root of the repo, instead of `data/scripts`

2022-11-15 07:32 UTC, DanMesh commented
@TSC21 This doesn't really belong in `tools`. It is a helper/convenience script to be installed and used _on Skynode_, whereas `tools` and `scripts` contain scripts to be used on development or build machines, which _aren't_ installed on Skynode.
`data` contains config files which do get installed, hence my choice to put it there.

If we want it kept elsewhere, I would suggest that we either:
1. create yet another folder (e.g. `helpers`) and use that for installed scripts, or
2. move the contents of `tools` to `scripts`, and then make `tools` the place we put "tools to be installed".

My preference would be for (2).

2022-11-15 07:43 UTC, TSC21 commented
> @TSC21 This doesn't really belong in `tools`. It is a helper/convenience script to be installed and used _on Skynode_, whereas `tools` and `scripts` contain scripts to be used on development or build machines, which _aren't_ installed on Skynode. `data` contains config files which do get installed, hence my choice to put it there.
> 
> If we want it kept elsewhere, I would suggest that we either:
> 
> 1. create yet another folder (e.g. `helpers`) and use that for installed scripts, or
> 2. move the contents of `tools` to `scripts`, and then make `tools` the place we put "tools to be installed".
> 
> My preference would be for (2).

`data` is relevant specially for the custom actions (that's why it was created in the first place). The point here is between what is optional and what is required at runtime. `tools`, the way I see it, can either be development tools or optional runtime tools as I can see it. And also we shouldn't make a distinctilm between Skynode install vs non-Skynode install as this is an open-source project.

What's inside `scripts` is used as part of the packaging process, so again a bit unrelated. I wonder if we should just merge `tools` and `scripts` together. Other than that, for me this script is still a `tool`, being it installed to be used runtime with the service or not.

2022-11-15 07:58 UTC, DanMesh commented
At the moment `tools` contains three scripts, all very much for development not runtime: two for code style checks and one for generating the debian changelog.

I'll go ahead with my option (2) above, as that seems to be the most sensible here.

2022-11-15 08:31 UTC, Andreea-L reviewed
A suggestion from my side on where to place the script: In remoteid-agent we have a [`tools` folder with a `devtools` subfolder](https://github.com/Auterion/remoteid-agent/tree/main/tools).
The netif script gets installed on device, while devtools separates out the helper scripts. And speaking of installation, you could make dpkg install `apm` into `/usr/bin/` as part of the Debian packaging process. You'd just need to add an `install` script in the `debian` folder with the contents:
```
tools/apm usr/bin
```

2022-11-15 08:31 UTC, Andreea-L commented on data/scripts/apm
> +if [[ ( $1 == "--help") ||  $1 == "-h" ]]
The no args and help case could be handled within the case statement, if written like so:
```suggestion
for i in "$@"; do
    case "$i" in
    update-config)
        update_config
        ;;
    safe-landing=*)
        safe_landing "${i#*=}"
        ;;
    help | h)
        display_usage
        exit 0
        ;;
    *)
        echo -e "Unexpected command '$i'.\n"
        display_usage
        exit 1
        ;;
    esac
done
```
This way the script also doesn't rely on args being strictly in the correct position ($1, $2, etc.).

For `safe-landing` the user would then supply the args like `apm safe-landing=enable`. Or you could change it to `enableD` if that reads better :D

2022-11-15 08:31 UTC, Andreea-L commented on data/scripts/apm
> +    exit 0
Do we need to `exit 0` here? Would the user ever want to do `apm update-config safe-landing=enable`? Because if so then the safe landing arg would never get parsed.

2022-11-15 10:50 UTC, DanMesh commented on data/scripts/apm
> +if [[ ( $1 == "--help") ||  $1 == "-h" ]]
Thanks, that's a good point.

Regarding the positional arguments, at the moment I'm thinking of this script as supporting "single action" calls. So it only does one thing at a time, and each subsequent argument identifies what that thing is.

For example, `safe-landing`, would not just be for enabling/disabling Safe Landing. I also see it being useful for parameter tuning or other functions.
So some example calls are
```sh
apm safe-landing enable
apm safe-landing std_dev_from_plane_thresh_m=0.055
apm safe-landing debug_mapper=True
```

2022-11-15 10:51 UTC, DanMesh commented on data/scripts/apm
> +    exit 0
As in my other comment, I wouldn't envisage these kinds of dual calls.
Nonetheless, it may be more extendable & readable to move the `exit` elsewhere

2022-11-15 11:00 UTC, Andreea-L commented on data/scripts/apm
> +if [[ ( $1 == "--help") ||  $1 == "-h" ]]
Hmmm I see your point. As you long as you clarify to a user that no extra apm args should go after `safe-landing` except for the args for the command, I suppose you could adapt the case like so... I haven't tested it but I think you should be able to supply a space as the splitting character in ` "${i#* }"`

```
         safe-landing *)
	        safe_landing "${i#* }"
	        ;;
```
Then inside the function you can do further processing

2022-11-15 11:01 UTC, DanMesh commented
> A suggestion from my side on where to place the script: In remoteid-agent we have a [tools folder with a devtools subfolder](https://github.com/Auterion/remoteid-agent/tree/main/tools).
> The netif script gets installed on device, while devtools separates out the helper scripts. And speaking of installation, you could make dpkg install apm into /usr/bin/ as part of the Debian packaging process. You'd just need to add an install script in the debian folder with the contents:
> 
> ```tools/apm usr/bin```

Thanks @Andreea-L.

I like that idea to consolidate it all into one `tools` directory. We'd already have a `packaging` subdirectory (from `scripts/packaging`) and could add another (e.g. `tools/devtools` or `tools/dev`) for the developer tools.

The Debian idea is also good, although at the moment we don't actually use the Debian packaging process. That's for the future!

2022-11-16 15:34 UTC, Andreea-L commented on tools/apm
> +        safe_landing ${@: 2}
Hmmm so this will forward all args as of the second one to `safe_landing`, but the function only parses the first arg anyway ($1), so maybe it can simply be:
```suggestion
        safe_landing $2
```

2022-11-16 15:39 UTC, DanMesh commented on tools/apm
> +        safe_landing ${@: 2}
Yes, it's only using the first one for now, but this leaves open the possibility to use more args in later iterations of the script.

2022-11-16 16:20 UTC, DanMesh commented on tools/apm
> +        safe_landing ${@: 2}
Sure - done ✅

2022-11-16 16:25 UTC, Andreea-L approved these changes

2022-11-16 16:55 UTC, merged